Add migration version number for rails 5.1
Since rails 5, migrations are versioned. For rails 5.1, the rails version of this migration has to be explicitly included. Otherwise, the following error will occur:

StandardError: Directly inheriting from ActiveRecord::Migration is not supported.

See http://blog.bigbinary.com/2016/03/01/migrations-are-versioned-in-rails-5.html for more details.